"""Figure generation for the diel-activity analysis.

EVERY figure in the paper and the report is generated by a function in this module. Nothing is
drawn ad hoc in a session. If a figure needs changing, change it here, rerun, and commit: the next
iteration then starts from working code instead of rebuilding from the data.

Usage
-----
    import dielfigs
    D = dielfigs.load_all(host)          # resolves inputs from the artifact store by name
    fig = dielfigs.fig02_species_curves(D)
    dielfigs.render_all(host, outdir="figs")

Conventions that are load-bearing
---------------------------------
SUN-ANCHORED TIME runs 0 = sunrise, 12 = sunset, 24 = next sunrise. Night is 12 to 24. Drawing it
as midnight-to-midnight puts nocturnal species in daylight; verify_curve_convention() checks this
against the stored measures and is called by every curve figure.

PEAK TIME (peak_h) is CIRCULAR. Never draw it on a linear sequential ramp; use CYCLIC_CMAP.

GUILD COLOURS are by behaviour, never by which analysis wave introduced a species.
"""
import json
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ---------------------------------------------------------------- constants

MEASURES = ["pct_noct", "pct_crep", "pct_noon", "conc", "peak_h"]

MEASURE_LABEL = {
    "pct_noct": "% of activity at night",
    "pct_crep": "% at dawn and dusk",
    "pct_noon": "% around midday",
    "conc": "concentration of activity",
    "peak_h": "time of the activity peak",
}

MECHANISM = {
    "pop_1km": "human disturbance",
    "nlcd_5k_crop": "agriculture",
    "tcc_1km": "vegetation",
    "rug_5km": "terrain",
    "tmax_hottest_month": "summer heat",
    "pred_richness": "predator richness",
    "pred_rate_total": "predator abundance",
    "log_det_rate": "relative abundance",
}

# Behavioural guilds. Boundaries set by the PI: under 20 percent of activity at night is diurnal,
# over 80 percent is nocturnal, between is intermediate.
GUILD_COLOUR = {"diurnal": "#D08C1F", "intermediate": "#4E9A6A", "nocturnal": "#3E5C93"}
GUILD_BOUNDS = (20.0, 80.0)

INK, MUTED = "#22303a", "#6b7a82"
CYCLIC_CMAP = "twilight"          # for peak_h ONLY
SEQ_CMAP = "viridis"
NIGHT_SHADE = "#e6e9eb"

# Inputs resolved from the artifact store by filename. Extend here, not in a session.
# Deployment start and end dates are needed for the seasonal-coverage panel and live in the raw
# export rather than in an artifact. Override with load_all(host, deployments_csv=...) if the
# export moves.
DEPLOYMENTS_CSV = ("/Users/rwkays/claude_code/activity_patterns/activity_data/"
                   "trend_data_arielle_used/combined_deployments_all.csv")

INPUTS = {
    "sites": "site_analysis_table_v2.csv",
    "harmonics": "stage2_harmonics_clean.csv",
    "effects": "all_partial_effects_v8.csv",
    "diagnostics": "model_diagnostics_v8.csv",
    "reliability": "stage2_metric_reliability.csv",
    "cv": "cv_results_v8.csv",
    "cv_mapping": "cv_results_mapping_model.csv",
    "null": "stage4_counting_noise_null.csv",
    "effort_corr": "count_predictor_effort_correlations.csv",
    "surfaces": "prediction_surfaces_v8.csv",
    "surface_diag": "prediction_surface_diagnostics_v8.csv",
    "abundance": "predator_abundance_effects.csv",
    "corr": "predictor_correlations_v8.csv",
    "grid": "grid_covariates_25km_seamfixed.csv",
    "arrays": "array_definition_v3.csv",
    "species": "species_final_counts.csv",
    "sources": "data_sources_used.csv",
    "excluded": "excluded_deployments.csv",
    "states": "viewer_states.json",
    "effort_nonuniform": "stage1_effort_nonuniformity.csv",
    "grid_4cov": "national_grid_covariates_4cov_25km.csv",
    "curve_shifts": "stage6_curve_shifts.csv",
    "null": "stage4_counting_noise_null.csv",
    "cv": "cv_results_v8.csv",
    "surface_diag": "prediction_surface_diagnostics_v8.csv",
    "surfaces": "prediction_surfaces_v8.csv",
}

# The five mappable environmental covariates and the grid column each lives in. They span two
# grid files joined on cell25: the seam-fixed grid carries population, canopy and temperature,
# the four-covariate grid carries cropland and ruggedness at 5 km.
# Row/column labels in predictor_correlations_v8.csv that correspond to the five MAPPED
# environmental conditions. The correlation matrix also carries the three count-derived
# predictors, which are not mapped.
ENV_LABELS = ["Population", "Cropland", "Tree canopy", "Ruggedness", "Summer heat"]

# The eight model predictors as they appear in the site table, the mechanism each stands for,
# and which enter on a log scale.
MODEL_PREDICTORS = ["pop_1km", "nlcd_5k_crop", "tcc_1km", "rug_5km", "tmax_hottest_month",
                    "pred_richness", "pred_rate_total", "log_det_rate"]
LOG_PREDICTORS = {"pop_1km", "pred_rate_total"}
MECH_OF = {"pop_1km": "human disturbance", "nlcd_5k_crop": "agriculture",
           "tcc_1km": "vegetation", "rug_5km": "terrain",
           "tmax_hottest_month": "summer heat", "pred_richness": "predator richness",
           "pred_rate_total": "predator abundance", "log_det_rate": "relative abundance"}

# The three count-derived predictors are NOT available on the prediction grid, and relative
# abundance is a property of the survey rather than of the landscape so it cannot be mapped in
# principle. They are shown as values at the 489 sites, never as national surfaces.
SITE_PREDICTORS = [
    ("pred_richness", "Predator richness", "carnivore species at the site", False, None),
    ("pred_rate_total", "Predator abundance", "carnivore detections per 100 camera-days",
     True, None),
    ("log_det_rate", "Relative abundance", "own detections per camera-hour, log",
     False, "White-tailed Deer"),
]

MAP_COVARIATES = [
    ("pop_1km", "grid", "Population density", "people per km2, log scale", True),
    ("ag_5km", "grid_4cov", "Cropland", "share of land within 5 km", False),
    ("tcc_1km", "grid", "Tree canopy", "percent cover", False),
    ("rug_5km", "grid_4cov", "Ruggedness", "terrain roughness index", False),
    ("t_warmmonth", "grid", "Summer heat", "max temperature of hottest month, C", False),
]


# ---------------------------------------------------------------- loading

def _resolve(host, filename):
    a = host.artifacts(filename=filename, exact=True, limit=6)
    if not a["artifacts"]:
        raise FileNotFoundError(f"no artifact named {filename!r}")
    best = sorted(a["artifacts"], key=lambda x: x["size_bytes"], reverse=True)[0]
    return host.artifact_path(best["latest_version_id"])


def load_all(host, extra=None, deployments_csv=DEPLOYMENTS_CSV):
    """Resolve and load every input. Returns a dict keyed as in INPUTS.

    `deployments_csv` supplies deployment start and end dates for the coverage panel. If the file
    is absent the panel is skipped and the rest of the figure still renders.
    """
    import os
    spec = dict(INPUTS)
    if extra:
        spec.update(extra)
    out = {}
    for key, fn in spec.items():
        path = _resolve(host, fn)
        if fn.endswith(".json"):
            with open(path) as fh:
                out[key] = json.load(fh)
        else:
            idx = 0 if key in ("species", "corr") else None
            out[key] = pd.read_csv(path, index_col=idx, low_memory=False)
    if deployments_csv and os.path.exists(deployments_csv):
        dep = pd.read_csv(deployments_csv, low_memory=False,
                          usecols=["project_id", "deployment_id", "start_date", "end_date"])
        dep["dep_key"] = dep.project_id.astype(str) + "|" + dep.deployment_id.astype(str)
        out["dep_dates"] = dep.drop_duplicates("dep_key").set_index("dep_key")[
            ["start_date", "end_date"]]
    else:
        out["dep_dates"] = None
    return out


# ---------------------------------------------------------------- curve helpers

def curve_grid(n=289):
    """Sun-anchored time grid in hours, 0 = sunrise, 12 = sunset."""
    t = np.linspace(0, 24, n)
    return t, 2 * np.pi * t / 24


def curves_from_harmonics(g, t=None):
    """Fitted activity curves from stored harmonic coefficients, rows normalised to sum to 1."""
    if t is None:
        t, _ = curve_grid()
    th = 2 * np.pi * t / 24
    M = np.exp(
        np.outer(g["s1"].values, np.sin(th)) + np.outer(g["c1"].values, np.cos(th))
        + np.outer(g["s2"].values, np.sin(2 * th)) + np.outer(g["c2"].values, np.cos(2 * th))
    )
    return M / M.sum(axis=1, keepdims=True)


def verify_curve_convention(harmonics, tol=1.0):
    """Night share recomputed from the curves must match the stored pct_noct.

    This exists because drawing sun-anchored time as midnight-to-midnight silently puts
    nocturnal species in daylight. Raises if the convention is wrong.
    """
    t, _ = curve_grid()
    night = (t >= 12) & (t < 24)
    rows = []
    for sp, g in harmonics.dropna(subset=["s1", "c1", "s2", "c2"]).groupby("species"):
        M = curves_from_harmonics(g, t)
        drawn = float((M[:, night].sum(axis=1) * 100).mean())
        rows.append((sp, drawn, float(g["pct_noct"].mean())))
    chk = pd.DataFrame(rows, columns=["species", "drawn", "stored"])
    chk["delta"] = (chk.drawn - chk.stored).abs()
    if chk.delta.max() > tol:
        worst = chk.loc[chk.delta.idxmax()]
        raise AssertionError(
            f"sun-time convention wrong: {worst.species} drawn {worst.drawn:.1f} "
            f"vs stored {worst.stored:.1f}. Night is sun-time 12 to 24, not 0-6 and 18-24."
        )
    return chk


def guild(pct_night):
    lo, hi = GUILD_BOUNDS
    return "diurnal" if pct_night < lo else ("nocturnal" if pct_night > hi else "intermediate")


def draw_states(ax, states_json, lw=0.45, color="#b9bfc4", zorder=1):
    """Lower-48 outlines in Albers space. Requires mapproj on the path."""
    import mapproj
    return mapproj.draw_states(ax, states_json, lw=lw, color=color, zorder=zorder)


def albers(lon, lat):
    import mapproj
    return mapproj.albers(lon, lat)


def _overlaps(fig):
    """Count text-text overlaps. Advisory: leader lines and math text give false positives."""
    r = fig.canvas.get_renderer()
    tt = [(x, x.get_window_extent(r)) for x in fig.findobj(mpl.text.Text)
          if x.get_text().strip() and x.get_visible()]
    return sum(1 for i, (_, ba) in enumerate(tt) for _, bb in tt[i + 1:] if ba.overlaps(bb))


# ---------------------------------------------------------------- figures

def fig01_data_coverage(D, style=None):
    """Where and when the data come from: site map, per-species counts, seasonal coverage."""
    if style:
        style()
    arrays, harm, spf, sources = D["arrays"], D["harmonics"], D["species"], D["sources"]
    used = set(harm.final_array.astype(str))
    sites = (arrays[arrays.final_array.astype(str).isin(used)]
             .groupby("final_array")
             .agg(lat=("latitude", "mean"), lon=("longitude", "mean"), ncam=("dep_key", "nunique"))
             .reset_index())
    sx, sy = albers(sites.lon.values, sites.lat.values)
    det_col = [c for c in spf.columns if "det" in c.lower()][0]
    d = spf.sort_values(det_col)
    nsit = harm.groupby("species").final_array.nunique().reindex(d.index)

    fig = plt.figure(figsize=(11.0, 8.6))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.55, 1], hspace=.26, wspace=.36)
    ax = fig.add_subplot(gs[0, :])
    ax.set_facecolor("#fbfbfa")
    draw_states(ax, D["states"])
    o = np.argsort(sites.ncam.values)
    sc = ax.scatter(sx[o], sy[o], s=5 + sites.ncam.values[o] * .75, c=sites.ncam.values[o],
                    cmap=SEQ_CMAP, lw=.25, edgecolor="white", alpha=.9, zorder=3)
    ax.set_xlim(-.385, .375); ax.set_ylim(-.225, .262)
    ax.set_aspect("equal"); ax.axis("off")
    cb = fig.colorbar(sc, ax=ax, fraction=.024, pad=.005, shrink=.82)
    cb.set_label("cameras at the site", fontsize=6.8); cb.ax.tick_params(labelsize=6)
    ndep = int(sources.deployments.sum())
    ax.set_title(f"a   {len(sites)} sites, {ndep:,} cameras that detected a study species, "
                 f"{len(sources)} projects", loc="left", fontsize=9)

    for i, (cell, ttl, col, vals, xlab) in enumerate([
            (gs[1, 0], "b   Detections per species", "#1f6f8b", d[det_col].values / 1000,
             "independent detections (thousands)"),
            (gs[1, 1], "c   Sites per species", "#2e7d4f", nsit.values,
             "sites with a fitted curve")]):
        a2 = fig.add_subplot(cell)
        a2.barh(range(len(vals)), vals, color=col, height=.74)
        a2.set_yticks(range(len(vals)))
        a2.set_yticklabels(d.index if i == 0 else [], fontsize=6.2)
        a2.set_xlabel(xlab); a2.set_title(ttl, loc="left", fontsize=9)

    ax = fig.add_subplot(gs[1, 2])
    dd = D.get("dep_dates")
    if dd is not None:
        keys = arrays[arrays.final_array.astype(str).isin(used)].dep_key.astype(str)
        sub = dd.reindex(keys).dropna()
        sd = pd.to_datetime(sub.start_date, errors="coerce")
        ed = pd.to_datetime(sub.end_date, errors="coerce")
        ok = sd.notna() & ed.notna()
        sd, ed = sd[ok], ed[ok]
    else:
        sd = None
    if sd is not None and len(sd):
        weeks = pd.date_range("2000-08-01", "2000-10-31", freq="W")
        cnt = [int(((sd.dt.dayofyear <= w.dayofyear) & (ed.dt.dayofyear >= w.dayofyear)).sum())
               for w in weeks]
        ax.fill_between(range(len(weeks)), cnt, color="#1f6f8b", alpha=.30)
        ax.plot(range(len(weeks)), cnt, color="#1f6f8b", lw=1.5)
        ax.set_xticks([0, 4, 8, 12])
        ax.set_xticklabels(["1 Aug", "1 Sep", "1 Oct", "31 Oct"], fontsize=6.4)
        ax.set_ylabel("cameras active"); ax.set_ylim(0, max(cnt) * 1.12)
    else:
        ax.axis("off")
        ax.text(.5, .5, "deployment export not available", ha="center", va="center",
                fontsize=7, color=MUTED, transform=ax.transAxes)
    ax.set_title("d   Coverage through the window", loc="left", fontsize=9)
    fig.suptitle("Where the data come from", fontsize=10.5, y=.955)
    return fig


def fig02_species_curves(D, style=None, n_show=200, seed=0):
    """The daily activity schedule of each species, sites behind the species average.

    Species are coloured by behavioural guild, never by analysis provenance.
    """
    if style:
        style()
    harm = D["harmonics"]
    verify_curve_convention(harm)
    t, _ = curve_grid()
    order = harm.groupby("species").pct_noct.mean().sort_values().index.tolist()
    rng = np.random.default_rng(seed)

    fig, axs = plt.subplots(4, 4, figsize=(13.6, 11.6), gridspec_kw=dict(hspace=.72, wspace=.30))
    for k, sp in enumerate(order):
        ax = axs.ravel()[k]
        g = harm[harm.species == sp].dropna(subset=["s1", "c1", "s2", "c2"])
        M = curves_from_harmonics(g, t)
        night_pct = float(g.pct_noct.mean())
        col = GUILD_COLOUR[guild(night_pct)]
        ax.axvspan(12, 24, color=NIGHT_SHADE, zorder=0, lw=0)
        sel = rng.choice(len(M), min(len(M), n_show), replace=False)
        for row in M[sel]:
            ax.plot(t, row * 1000, color=col, lw=.35, alpha=.15, zorder=2)
        mu = M.mean(axis=0) * 1000
        ax.plot(t, mu, color=col, lw=2.3, zorder=4, solid_capstyle="round")
        ax.set_title(f"{sp}\n{night_pct:.0f}% of activity at night  \u00b7  {len(g)} sites",
                     loc="left", fontsize=7.3, pad=4, color=col)
        ax.set_xlim(0, 24); ax.set_xticks([0, 6, 12, 18, 24])
        ax.set_xticklabels(["sunrise", "noon", "sunset", "midnight", "sunrise"], fontsize=5.8)
        ax.set_ylim(0, max(mu.max() * 2.3, 1)); ax.tick_params(axis="y", labelsize=5.8)
        if k % 4 == 0:
            ax.set_ylabel("share of daily activity\n(per mille per half hour)", fontsize=6.1)
    for k in range(len(order), 16):
        axs.ravel()[k].axis("off")
    lo, hi = GUILD_BOUNDS
    lab = {"diurnal": f"diurnal (under {lo:.0f}% at night)",
           "intermediate": f"intermediate ({lo:.0f} to {hi:.0f}%)",
           "nocturnal": f"nocturnal (over {hi:.0f}%)"}
    axs.ravel()[15].legend(
        handles=[Line2D([], [], color=GUILD_COLOUR[g_], lw=2.3, label=lab[g_])
                 for g_ in ["diurnal", "intermediate", "nocturnal"]]
        + [Line2D([], [], color=MUTED, lw=1.0, alpha=.6, label="one site"),
           Patch(facecolor=NIGHT_SHADE, edgecolor="none", label="hours of darkness")],
        fontsize=7.2, frameon=False, loc="center left")
    fig.suptitle("The daily activity schedule of each species, and how much sites differ within it",
                 fontsize=11, y=.995)
    return fig


def fig03_effort_offset(D, style=None, binned_suntime=None, binned_clock=None):
    """Why sun-anchored time needs a per-bin effort offset.

    Panel a needs the binned tables, which are large; pass them in rather than loading here.
    If they are absent the panel is replaced by a note and panel b still renders from the
    summary table.
    """
    if style:
        style()
    nu = D["effort_nonuniform"]
    dep = nu[nu.level == "deployment"].iloc[0]

    fig, axes = plt.subplots(1, 2, figsize=(11.2, 3.9), gridspec_kw=dict(wspace=.30))
    ax = axes[0]
    if binned_suntime is not None:
        g = binned_suntime.sort_values("bin")
        ax.step(g["bin"], g.effort_h, where="mid", color="#1f6f8b", lw=1.6,
                label="sun-anchored time")
        if binned_clock is not None:
            gc = binned_clock.sort_values("bin")
            ax.step(gc["bin"], gc.effort_h, where="mid", color=MUTED, lw=1.4, ls="--",
                    label="clock time")
        ax.axvspan(24, 48, color=NIGHT_SHADE, zorder=0, lw=0)
        ax.set_xlim(0, 48); ax.set_xticks([0, 12, 24, 36, 48])
        ax.set_xticklabels(["sunrise", "noon", "sunset", "midnight", "sunrise"], fontsize=6.4)
        ax.set_ylabel("camera hours in the bin")
        ax.set_ylim(0, g.effort_h.max() * 1.25)
        ax.legend(fontsize=6.4, frameon=False, loc="upper left")
        ratio = g.effort_h.max() / g.effort_h.min()
        ax.set_title(f"a   One camera: effort is flat on the clock,\nnot in sun time "
                     f"({ratio:.2f} times more in the widest bin)", loc="left", fontsize=8.4)
    else:
        ax.axis("off")
        ax.text(.5, .5, "binned tables not supplied", ha="center", va="center",
                fontsize=7, color=MUTED, transform=ax.transAxes)

    ax = axes[1]
    vals = [dep["median"], dep["p99"], dep["max"]]
    labs = ["typical camera\n(median)", "99th\npercentile", "worst\ncamera"]
    ax.bar(range(3), vals, color=["#9dbcc9", "#4d8fa6", "#1f6f8b"], width=.62)
    for i, v in enumerate(vals):
        ax.text(i, v + .06, f"{v:.2f}x", ha="center", fontsize=7.2, color=INK)
    ax.axhline(1.0, color="#b5442e", lw=1.0, ls=":")
    ax.text(-0.42, 0.94, "equal effort in every bin", fontsize=6.2, color="#b5442e",
            ha="left", va="top")
    ax.set_xticks(range(3)); ax.set_xticklabels(labs, fontsize=6.4)
    ax.set_ylabel("most crowded bin / emptiest bin")
    ax.set_ylim(0, max(vals) * 1.22)
    ax.set_title("b   How unequal the bins get,\nacross all 22,912 cameras", loc="left",
                 fontsize=8.4)
    fig.suptitle("Rescaling the day to sunrise and sunset makes the time bins unequal",
                 fontsize=10, y=1.04)
    return fig


def fig04_measures_reliability(D, style=None, example_species="Coyote", min_events=300):
    """What the five measures read off a curve, and which are reliable enough to model.

    Panel b contrasts a nearly flat curve with a sharply peaked one, both from well-measured
    site-species combinations, because "concentration" is the measure a reader is least likely
    to picture from a definition alone.
    """
    if style:
        style()
    harm, rel, sites = D["harmonics"], D["reliability"], D["sites"]
    t, _ = curve_grid()

    def site_curve(species, site):
        g = harm[(harm.species == species) & (harm.final_array.astype(str) == str(site))]
        g = g.dropna(subset=["s1", "c1", "s2", "c2"])
        if not len(g):
            return None
        v = curves_from_harmonics(g, t)[0]
        return v / v.sum() * 1000

    fig = plt.figure(figsize=(13.6, 4.3))
    gs = fig.add_gridspec(1, 3, width_ratios=[1, 1, 1.35], wspace=.30)

    # (a) the five measures annotated on one species-average curve
    ax = fig.add_subplot(gs[0, 0])
    g = harm[harm.species == example_species].dropna(subset=["s1", "c1", "s2", "c2"])
    mu = curves_from_harmonics(g, t).mean(axis=0)
    mu = mu / mu.sum() * 1000
    ax.axvspan(12, 24, color=NIGHT_SHADE, zorder=0, lw=0)
    ax.plot(t, mu, color=INK, lw=2.2, zorder=4)
    ax.fill_between(t, 0, mu, where=(t >= 12), color="#3E5C93", alpha=.30, zorder=2)
    for lo, hi in [(0, 2), (10, 12)]:
        ax.fill_between(t, 0, mu, where=((t >= lo) & (t <= hi)), color="#D08C1F",
                        alpha=.45, zorder=3)
    ax.fill_between(t, 0, mu, where=((t >= 5) & (t <= 7)), color="#4E9A6A", alpha=.45, zorder=3)
    pk = float(t[np.argmax(mu)])
    ax.annotate("", xy=(pk, mu.max()), xytext=(pk, mu.max() * 1.26),
                arrowprops=dict(arrowstyle="->", color="#b5442e", lw=1.2))
    ax.text(pk, mu.max() * 1.30, "time of peak", ha="center", fontsize=6.6, color="#b5442e")
    ax.text(18, mu.max() * .32, "share at night", ha="center", fontsize=6.6, color="white")
    ax.text(1.0, mu.max() * .52, "dawn", ha="center", fontsize=6.0, color=INK)
    ax.text(11.0, mu.max() * .52, "dusk", ha="center", fontsize=6.0, color=INK)
    ax.text(6.0, mu.max() * .22, "midday", ha="center", fontsize=6.0, color=INK)
    ax.set_xlim(0, 24); ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xticklabels(["sunrise", "noon", "sunset", "midnight", "sunrise"], fontsize=6.4)
    ax.set_ylim(0, mu.max() * 1.48)
    ax.set_ylabel("share of daily activity")
    ax.set_title(f"a   Four measures read off one curve\n({example_species} average)",
                 loc="left", fontsize=8.6)

    # (b) concentration: flat against peaked, both well measured
    ax = fig.add_subplot(gs[0, 1])
    w = sites.dropna(subset=["conc"])
    w = w[w.n_events >= min_events]
    lo_r = w.nsmallest(1, "conc").iloc[0]
    hi_r = w.nlargest(1, "conc").iloc[0]
    drew = 0
    for r_, col, tag in [(lo_r, "#4E9A6A", "spread through the day"),
                         (hi_r, "#b5442e", "concentrated in a few hours")]:
        v = site_curve(r_.species, r_.final_array)
        if v is None:
            continue
        drew += 1
        ax.plot(t, v, color=col, lw=2.2, zorder=4)
        ax.fill_between(t, 0, v, color=col, alpha=.16, zorder=2)
        y0 = .96 - .135 * (drew - 1)
        ax.text(.03, y0, f"concentration {r_.conc:.2f}   {tag}",
                transform=ax.transAxes, fontsize=6.6, color=col, va="top")
        ax.text(.03, y0 - .058,
                f"{r_.species}, one site, {int(r_.n_events):,} detections",
                transform=ax.transAxes, fontsize=5.7, color=MUTED, va="top")
    ax.axvspan(12, 24, color=NIGHT_SHADE, zorder=0, lw=0)
    ax.set_xlim(0, 24); ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xticklabels(["sunrise", "noon", "sunset", "midnight", "sunrise"], fontsize=6.4)
    ax.set_ylabel("share of daily activity")
    ax.set_ylim(0, ax.get_ylim()[1] * 1.34)
    ax.set_title("b   The fifth measure, concentration:\nhow much of the day the animal uses",
                 loc="left", fontsize=8.6)

    # (c) reliability
    ax = fig.add_subplot(gs[0, 2])
    piv = rel.pivot(index="species", columns="metric", values="reliability")
    cols = [c for c in MEASURES if c in piv.columns]
    piv = piv[cols].loc[piv[cols].mean(axis=1).sort_values().index]
    for i, sp in enumerate(piv.index):
        for j, mm in enumerate(cols):
            v = piv.loc[sp, mm]
            if not np.isfinite(v):
                continue
            passes = v >= 0.5
            ax.scatter(j, i, s=42 + 150 * min(max(v, 0), 1),
                       c="#1f6f8b" if passes else "#ffffff",
                       edgecolor="#1f6f8b" if passes else "#b5442e",
                       lw=.9 if passes else 1.4, zorder=3)
            if not passes:
                ax.text(j, i, "x", ha="center", va="center", fontsize=5.6, color="#b5442e",
                        zorder=4)
    ax.set_xticks(range(len(cols)))
    ax.set_xticklabels([MEASURE_LABEL[c].replace("% of activity ", "").replace("% ", "")
                        for c in cols], fontsize=6.2, rotation=18, ha="right")
    ax.set_yticks(range(len(piv.index))); ax.set_yticklabels(piv.index, fontsize=6.2)
    ax.set_xlim(-.6, len(cols) - .4)
    nfail = int((rel[rel.metric.isin(cols)].reliability < 0.5).sum())
    act = rel[rel.metric == "act"]
    ylim_hi = len(piv.index) - .3
    if len(act):
        ya = len(piv.index) + .55
        ax.axhline(len(piv.index) - .1, color="#d5d9dc", lw=.8)
        ax.scatter([1.0], [ya], s=42 + 150 * float(act.reliability.median()),
                   c="#ffffff", edgecolor="#b5442e", lw=1.4, zorder=3)
        ax.text(1.0, ya, "x", ha="center", va="center", fontsize=5.6, color="#b5442e", zorder=4)
        ax.text(1.35, ya, f"overall activity level, median {act.reliability.median():.2f}\n"
                          f"excluded from all spatial analysis",
                fontsize=5.7, color="#b5442e", va="center")
        ylim_hi = ya + .7
    ax.set_ylim(-.7, ylim_hi)
    ax.set_title(f"c   Reliability: is a site's value real, or counting noise?\n"
                 f"Larger is more reliable; {nfail} of {len(cols) * len(piv.index)} "
                 f"combinations fall below 0.5 and are not modelled", loc="left", fontsize=8.6)
    fig.suptitle("What the measures are, and which ones the data can support",
                 fontsize=10, y=1.03)
    return fig

def fig05_covariate_maps(D, style=None):
    """The eight model predictors: five as national surfaces, three as site values.

    The split is not cosmetic. Predator richness, predator abundance and relative abundance are
    not available on the prediction grid, so only the five environmental covariates can carry a
    surface; relative abundance cannot be mapped in principle.
    """
    if style:
        style()
    gj = D["grid"][["cell25", "lon", "lat", "pop_1km", "tcc_1km", "t_warmmonth"]].merge(
        D["grid_4cov"][["cell25", "ag_5km", "rug_5km"]], on="cell25", how="left")
    gx, gy = albers(gj.lon.values, gj.lat.values)

    sites = D["sites"]
    harm = D["harmonics"]
    xy = harm.groupby("final_array").agg(lat=("lat", "first"), lon=("lon", "first"))

    fig = plt.figure(figsize=(13.0, 9.4))
    gs = fig.add_gridspec(3, 3, hspace=.22, wspace=.06)

    def _basemap(ax):
        draw_states(ax, D["states"], lw=.30, color="#c9cfd4")
        ax.set_xlim(-.385, .375); ax.set_ylim(-.225, .262)
        ax.set_aspect("equal"); ax.axis("off")

    for k, (col, _src, title, unit, logscale) in enumerate(MAP_COVARIATES):
        ax = fig.add_subplot(gs[k // 3, k % 3])
        v = gj[col].values.astype(float)
        ok = np.isfinite(v)
        vv = np.log10(v[ok] + 1) if logscale else v[ok]
        _basemap(ax)
        hi_pct = 99.8 if logscale else 98.0
        top = np.nanpercentile(vv, hi_pct)
        sc = ax.scatter(gx[ok], gy[ok], c=vv, s=1.5, cmap=SEQ_CMAP, lw=0,
                        vmin=np.nanpercentile(vv, 2), vmax=top)
        cb = fig.colorbar(sc, ax=ax, fraction=.030, pad=.005, shrink=.72)
        cb.ax.tick_params(labelsize=5.4)
        if logscale:
            tk = [np.log10(x + 1) for x in [0, 1, 3, 10, 30, 100] if np.log10(x + 1) <= top]
            cb.set_ticks(tk)
            cb.set_ticklabels([f"{10 ** t_ - 1:,.0f}" for t_ in tk], fontsize=5.4)
        ax.set_title(f"{'abcdefgh'[k]}   {title}", loc="left", fontsize=8.2)
        ax.text(.02, .02, unit + (" (log)" if logscale else ""), transform=ax.transAxes,
                fontsize=5.8, color=MUTED)

    # correlation panel in the free slot of row 2
    ax = fig.add_subplot(gs[1, 2])
    C = D["corr"]
    M = C.values.astype(float)
    diag = np.eye(len(C), dtype=bool)
    Mm = np.ma.masked_where(np.triu(np.ones_like(M, dtype=bool)), M)
    im = ax.imshow(Mm, cmap="RdBu_r", vmin=-.6, vmax=.6)
    ax.set_xticks(range(len(C))); ax.set_yticks(range(len(C)))
    ax.set_xticklabels(C.columns, fontsize=5.0, rotation=45, ha="right")
    ax.set_yticklabels(C.index, fontsize=5.0)
    ax.set_xlim(-.6, len(C) - 1.4); ax.set_ylim(len(C) - .4, .6)
    for i in range(len(C)):
        for j in range(i):
            ax.text(j, i, f"{M[i, j]:.2f}", ha="center", va="center", fontsize=5.0,
                    color="white" if abs(M[i, j]) > .35 else INK)
    cb = fig.colorbar(im, ax=ax, fraction=.030, pad=.02, shrink=.72)
    cb.ax.tick_params(labelsize=5.4)
    i_f, j_f = np.unravel_index(np.nanargmax(np.abs(np.where(~diag, M, np.nan))), M.shape)
    env = [c for c in ENV_LABELS if c in C.index]
    Me = C.loc[env, env].values.astype(float)
    oe = ~np.eye(len(env), dtype=bool)
    i_e, j_e = np.unravel_index(np.nanargmax(np.abs(np.where(oe, Me, np.nan))), Me.shape)
    ax.set_title(f"f   Overlap among all eight predictors\n"
                 f"largest {abs(M[i_f, j_f]):.2f} ({C.index[i_f]} vs {C.columns[j_f]}); "
                 f"among the five mapped {abs(Me[i_e, j_e]):.2f}", loc="left", fontsize=7.2)

    # row 3: the three count-derived predictors, at sites only
    for k, (col, title, unit, logscale, species) in enumerate(SITE_PREDICTORS):
        ax = fig.add_subplot(gs[2, k])
        sub = sites if species is None else sites[sites.species == species]
        agg = (sub.groupby("final_array")[col].mean() if species is None
               else sub.set_index("final_array")[col])
        dd = agg.to_frame("v").join(xy, how="inner").dropna()
        v = np.log10(dd.v.values + 1) if logscale else dd.v.values
        px, py = albers(dd.lon.values, dd.lat.values)
        _basemap(ax)
        o = np.argsort(v)
        sc = ax.scatter(px[o], py[o], c=v[o], s=13, cmap="magma_r", lw=.25,
                        edgecolor="white", zorder=3,
                        vmin=np.nanpercentile(v, 2), vmax=np.nanpercentile(v, 98))
        cb = fig.colorbar(sc, ax=ax, fraction=.030, pad=.005, shrink=.72)
        cb.ax.tick_params(labelsize=5.4)
        if logscale:
            tk = [np.log10(x + 1) for x in [0, 1, 3, 10, 30, 100]
                  if np.log10(x + 1) <= np.nanpercentile(v, 98)]
            cb.set_ticks(tk)
            cb.set_ticklabels([f"{10 ** t_ - 1:,.0f}" for t_ in tk], fontsize=5.4)
        ax.set_title(f"{'abcdefghi'[6 + k]}   {title}", loc="left", fontsize=8.2)
        sp_note = f"{species}\n" if species else ""
        ax.text(.02, .02, f"{sp_note}{unit}\n{len(dd)} sites, no national layer",
                transform=ax.transAxes, fontsize=5.6, color=MUTED)

    fig.text(.008, .655, "national surfaces", rotation=90, fontsize=7.4, color=MUTED,
             va="center")
    fig.text(.008, .175, "site values only", rotation=90, fontsize=7.4, color="#b5442e",
             va="center")
    fig.suptitle("The eight model predictors: five can be mapped nationally, three only "
                 "where cameras were placed", fontsize=10, y=.945)
    return fig


def fig06_timestamp_qc(D, style=None):
    """The camera clocks that were wrong, where they were, and what removing them did.

    Panel b is drawn from stage6_curve_shifts.csv rather than embedding a rendered figure, so
    it scales with the rest of the set.
    """
    if style:
        style()
    ex, arrays, cs = D["excluded"], D["arrays"], D["curve_shifts"]
    coords = arrays.drop_duplicates("dep_key")
    coords = coords.set_index(coords.dep_key.astype(str))
    hit = coords.reindex(ex.dep_key.astype(str)).dropna(subset=["latitude", "longitude"])
    px, py = albers(hit.longitude.values, hit.latitude.values)

    fig, axes = plt.subplots(1, 3, figsize=(13.4, 4.2),
                             gridspec_kw=dict(width_ratios=[1.15, 1, .85], wspace=.28))
    ax = axes[0]
    draw_states(ax, D["states"], lw=.35, color="#c9cfd4")
    a_, b_ = albers(coords.longitude.values, coords.latitude.values)
    ax.scatter(a_, b_, s=.7, c="#dde1e4", lw=0, zorder=2)
    ax.scatter(px, py, s=30, c="#b5442e", lw=.35, edgecolor="white", zorder=4)
    ax.set_xlim(-.385, .375); ax.set_ylim(-.225, .262)
    ax.set_aspect("equal"); ax.axis("off")
    nproj = ex.wi_project_title.nunique() if "wi_project_title" in ex.columns else np.nan
    ax.set_title(f"a   {len(hit)} excluded cameras across {nproj:.0f} projects\n"
                 f"(grey: every other camera)", loc="left", fontsize=8.4)

    # (b) each affected curve, before against after
    ax = axes[1]
    for g_, col in [("diurnal", GUILD_COLOUR["diurnal"]),
                    ("intermediate", GUILD_COLOUR["intermediate"]),
                    ("nocturnal", GUILD_COLOUR["nocturnal"])]:
        sub = cs[cs.guild == g_]
        ax.scatter(sub.pct_noct_pre, sub.d, s=13, c=col, lw=0, alpha=.85,
                   label=f"{g_} ({len(sub)})", zorder=3)
    ax.axhline(0, color=MUTED, lw=.8, ls="--")
    ax.set_xlabel("% of activity at night before the exclusions")
    ax.set_ylabel("change after the exclusions\n(percentage points)")
    ax.legend(fontsize=6.2, frameon=False, loc="upper left")
    ax.set_title("b   Every affected curve moved toward\nits species' real rhythm",
                 loc="left", fontsize=8.4)

    # (c) the direction test
    ax = axes[2]
    gl = ["diurnal", "intermediate", "nocturnal"]
    med = [cs[cs.guild == g_].d.median() for g_ in gl]
    ax.barh(range(3), med, color=[GUILD_COLOUR[g_] for g_ in gl], height=.62)
    ax.axvline(0, color=INK, lw=.9)
    for i, (g_, v) in enumerate(zip(gl, med)):
        n_ = int((cs[cs.guild == g_].d < 0).sum()) if g_ == "diurnal" \
            else int((cs[cs.guild == g_].d > 0).sum())
        tot = int((cs.guild == g_).sum())
        ax.text(v, i - .40, f"{n_} of {tot} in the expected direction",
                va="bottom", ha="left" if v >= 0 else "right", fontsize=5.8, color=MUTED)
    ax.set_yticks(range(3)); ax.set_yticklabels(gl, fontsize=6.6)
    ax.set_xlabel("median change in % at night\n(percentage points)")
    lo_x, hi_x = min(med) * 1.9 - .4, max(med) * 1.9 + .4
    ax.set_xlim(lo_x, hi_x)
    ax.set_title("c   Diurnal species lost false night activity;\nnocturnal species regained real "
                 "night activity", loc="left", fontsize=8.4)
    n_dn = int(((cs.guild == "diurnal") & (cs.d < 0)).sum())
    n_d = int((cs.guild == "diurnal").sum())
    n_nn = int(((cs.guild == "nocturnal") & (cs.d > 0)).sum())
    n_n = int((cs.guild == "nocturnal").sum())
    fig.suptitle(f"Finding and removing cameras whose clocks were wrong: {len(cs)} curves moved, "
                 f"{n_dn} of {n_d} diurnal downward and {n_nn} of {n_n} nocturnal upward",
                 fontsize=9.6, y=1.03)
    return fig

def fig07_model_effects(D, style=None):
    """What the model found: effect direction and strength, by mechanism."""
    if style:
        style()
    e = D["effects"].copy()
    order = (e.groupby("mechanism").sig.sum().sort_values(ascending=False).index.tolist())

    fig, axes = plt.subplots(1, 2, figsize=(12.8, 4.6),
                             gridspec_kw=dict(width_ratios=[1.15, 1], wspace=.30))
    # (a) how many effects each mechanism carries, and how many survive the geography control
    ax = axes[0]
    y = np.arange(len(order))
    tot = [int((e.mechanism == mm).sum()) for mm in order]
    sig = [int(e[e.mechanism == mm].sig.sum()) for mm in order]
    sur = [int(e[e.mechanism == mm].survives_spatial.sum()) for mm in order]
    ax.barh(y, tot, color="#eceff1", height=.70, label="fitted (61 per mechanism)")
    ax.barh(y, sig, color="#7fa9bb", height=.70, label="statistically clear")
    ax.barh(y, sur, color="#1f6f8b", height=.70, label="and still clear with geography held")
    for i, (s_, u_) in enumerate(zip(sig, sur)):
        ax.text(s_ + 1.2, i, f"{s_}", va="center", fontsize=6.6, color="#4a6b78")
        if u_:
            ax.text(u_ / 2, i, f"{u_}", va="center", ha="center", fontsize=6.4, color="white")
    ax.set_yticks(y); ax.set_yticklabels(order, fontsize=7)
    ax.invert_yaxis(); ax.set_xlabel("species-measure combinations (of 61)")
    ax.legend(fontsize=6.2, frameon=False, loc="lower right")
    ax.set_title("a   How many effects each mechanism carries", loc="left", fontsize=8.8)

    # (b) partial R2: the share of site-to-site variation a mechanism explains on its own
    ax = axes[1]
    for i, mm in enumerate(order):
        v = e[e.mechanism == mm].partial_r2.dropna().values
        xj = np.random.default_rng(i).normal(0, .075, len(v))
        s_ = e[e.mechanism == mm]
        clear = s_.sig.fillna(False).values.astype(bool)
        pr = s_.partial_r2.values
        ax.scatter(pr[~clear], i + xj[:len(pr)][~clear], s=8, c="#ffffff",
                   edgecolor="#c3cbd0", lw=.5, zorder=2)
        ax.scatter(pr[clear], i + xj[:len(pr)][clear], s=13, c="#1f6f8b", lw=0, zorder=3)
        ax.plot([np.nanmedian(v)], [i], marker="|", ms=13, color=INK, zorder=4)
    ax.set_yticks(range(len(order))); ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel("share of site-to-site variation explained on its own\n"
                  "with the other seven mechanisms held constant")
    ax.set_xlim(-.01, min(0.42, float(np.nanpercentile(e.partial_r2, 99.5))))
    ax.legend(handles=[Line2D([], [], marker="o", ls="", mfc="#1f6f8b", mec="#1f6f8b", ms=4,
                              label="statistically clear"),
                       Line2D([], [], marker="o", ls="", mfc="white", mec="#c3cbd0", ms=4,
                              label="not clear"),
                       Line2D([], [], marker="|", ls="", color=INK, ms=9, label="median")],
              fontsize=6.2, frameon=False, loc="upper right",
              bbox_to_anchor=(1.0, 1.02))
    ax.set_title("b   How much each mechanism explains", loc="left", fontsize=8.8)
    ntot, nsig, nsur = len(e), int(e.sig.sum()), int(e.survives_spatial.sum())
    fig.suptitle(f"Eight mechanisms across 61 models: {nsig} of {ntot} effects are "
                 f"statistically clear, {nsur} survive holding geography constant",
                 fontsize=10, y=1.02)
    return fig


def fig08_predator_abundance(D, style=None, focal="Eastern Fox Squirrel"):
    """Predator abundance: the effects, one species in detail, and its overlap with richness."""
    if style:
        style()
    pab, sites, harm = D["abundance"], D["sites"], D["harmonics"]
    sig = pab[pab.significant.fillna(False)].copy()
    sig["label"] = sig.species + "\n" + sig.measure.map(MEASURE_LABEL).fillna(sig.measure)
    sig = sig.sort_values("partial_r2")

    fig = plt.figure(figsize=(13.4, 4.5))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.15, 1, 1], wspace=.34)

    # (a) the significant effects with intervals
    ax = fig.add_subplot(gs[0, 0])
    y = np.arange(len(sig))
    ax.errorbar(sig.beta, y, xerr=[sig.beta - sig.lo, sig.hi - sig.beta], fmt="o",
                ms=5, lw=1.1, color="#1f6f8b", ecolor="#7fa9bb", capsize=2)
    ax.axvline(0, color="#b5442e", lw=.9, ls=":")
    for i, (_, r_) in enumerate(sig.iterrows()):
        ax.text(r_.hi + (sig.hi.max() - sig.lo.min()) * .03, i,
                f"R2 {r_.partial_r2:.3f}", va="center", fontsize=6.0, color=MUTED)
    ax.set_yticks(y); ax.set_yticklabels(sig.label, fontsize=6.0)
    ax.set_xlabel("change in the measure per unit of predator abundance")
    ax.set_title(f"a   The {len(sig)} clear predator-abundance effects", loc="left",
                 fontsize=8.6)

    # (b) the focal species' curves at low against high predator abundance
    ax = fig.add_subplot(gs[0, 1])
    t, _ = curve_grid()
    sub = sites[sites.species == focal].dropna(subset=["pred_rate_total"])
    q1, q3 = sub.pred_rate_total.quantile([.25, .75])
    hh = harm[harm.species == focal].dropna(subset=["s1", "c1", "s2", "c2"])
    hh = hh.merge(sub[["final_array", "pred_rate_total"]], on="final_array", how="inner")
    ax.axvspan(12, 24, color=NIGHT_SHADE, zorder=0, lw=0)
    for grp, col, lab in [(hh[hh.pred_rate_total <= q1], "#4E9A6A", "few predators"),
                          (hh[hh.pred_rate_total >= q3], "#b5442e", "many predators")]:
        if not len(grp):
            continue
        M = curves_from_harmonics(grp, t)
        M = M / M.sum(axis=1, keepdims=True)
        mu = M.mean(axis=0) * 1000
        ax.plot(t, mu, color=col, lw=2.2, zorder=4,
                label=f"{lab} ({len(grp)} sites)")
        ax.fill_between(t, 0, mu, color=col, alpha=.13, zorder=2)
    ax.set_xlim(0, 24); ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xticklabels(["sunrise", "noon", "sunset", "midnight", "sunrise"], fontsize=6.4)
    ax.set_ylabel("share of daily activity")
    ax.legend(fontsize=6.4, frameon=False, loc="upper right")
    ax.set_title(f"b   {focal}: where predators are common,\nactivity shifts toward midday",
                 loc="left", fontsize=8.6)

    # (c) richness against abundance, and which effects each carries
    ax = fig.add_subplot(gs[0, 2])
    ss = sites.drop_duplicates("final_array").dropna(subset=["pred_richness",
                                                             "pred_rate_total"])
    ax.scatter(ss.pred_richness + np.random.default_rng(0).normal(0, .09, len(ss)),
               np.log1p(ss.pred_rate_total), s=8, c="#7fa9bb", lw=0, alpha=.7)
    # Two correlations, both correct for what they describe. The panel plots one point per
    # SITE, so quote that; the methods table reports the value over the MODEL rows, where
    # sites contributing more species-measure combinations weigh more heavily.
    r_site = float(np.corrcoef(ss.pred_richness, np.log1p(ss.pred_rate_total))[0, 1])
    zz = sites[["pred_richness", "pred_rate_total"]].dropna()
    r_model = float(np.corrcoef(zz.pred_richness, np.log1p(zz.pred_rate_total))[0, 1])
    ax.set_xlabel("predator richness (species at the site)")
    ax.set_ylabel("predator abundance (detections per 100\ncamera-days, log scale)")
    only_a = int(((pab.significant.fillna(False)) & (~pab.richness_significant.fillna(False))).sum())
    only_r = int(((~pab.significant.fillna(False)) & (pab.richness_significant.fillna(False))).sum())
    both = int(((pab.significant.fillna(False)) & (pab.richness_significant.fillna(False))).sum())
    ax.text(.03, .97, f"correlation {r_site:+.2f} across the {len(ss)} sites shown\n"
                      f"({r_model:+.2f} across model rows, as in the methods)\n\n"
                      f"{only_r} combinations carry richness only\n"
                      f"{only_a} carry abundance only\n{both} carry both",
            transform=ax.transAxes, fontsize=6.2, va="top", color=INK)
    ax.set_title("c   Richness and abundance are\nnearly independent", loc="left",
                 fontsize=8.6)
    fig.suptitle("Predator abundance is a separate signal from how many predator species "
                 "are present", fontsize=10, y=1.02)
    return fig


def local_variability(sites, predictors=None, radius_km=50):
    """How much each predictor changes between sites closer than `radius_km`, against its
    national spread.

    This is the quantity that decides whether a position spline can absorb a predictor. A
    predictor that varies only over long distances is a smooth function of position, so the
    spline reproduces it and the partial coefficient loses its footing. One that differs
    between neighbouring sites carries information position does not.
    """
    from scipy.spatial import cKDTree
    predictors = predictors or MODEL_PREDICTORS
    st = sites.drop_duplicates("final_array")
    st = st[["final_array", "x_km", "y_km"] + list(predictors)].dropna(subset=["x_km", "y_km"])
    pairs = cKDTree(np.c_[st.x_km, st.y_km]).query_pairs(r=radius_km, output_type="ndarray")
    rows = []
    for c in predictors:
        v = st[c].values.astype(float)
        if c in LOG_PREDICTORS:
            v = np.log1p(v)
        tot = np.nanstd(v, ddof=1)
        ok = np.isfinite(v[pairs[:, 0]]) & np.isfinite(v[pairs[:, 1]])
        d = np.abs(v[pairs[:, 0]][ok] - v[pairs[:, 1]][ok])
        local = np.sqrt(np.mean(d ** 2) / 2) if len(d) else np.nan
        rows.append((MECH_OF.get(c, c), c, tot, local, local / tot if tot else np.nan))
    out = pd.DataFrame(rows, columns=["mechanism", "predictor", "sd_total",
                                      "sd_local", "ratio"])
    out.attrs["n_pairs"] = int(len(pairs))
    out.attrs["radius_km"] = radius_km
    return out.sort_values("ratio", ascending=False)


def fig09_spatial_control(D, style=None, radius_km=50):
    """Why some mechanisms survive holding geography constant and others do not.

    The earlier version of panel a plotted each coefficient against its own value under the
    position control, which can only fall near the identity line and says nothing. It is
    replaced by the property that actually decides the outcome: how locally variable the
    predictor is.
    """
    if style:
        style()
    e = D["effects"]
    LV = local_variability(D["sites"], radius_km=radius_km)
    n_pairs = LV.attrs["n_pairs"]   # merge below drops DataFrame.attrs
    surv = e.groupby("mechanism").agg(sig=("sig", "sum"), sur=("survives_spatial", "sum"))
    surv["pct"] = 100 * surv.sur / surv.sig.replace(0, np.nan)
    LV = LV.merge(surv.reset_index(), on="mechanism", how="left")
    order = e.groupby("mechanism").sig.sum().sort_values(ascending=False).index.tolist()

    fig, axes = plt.subplots(1, 3, figsize=(13.4, 4.3),
                             gridspec_kw=dict(width_ratios=[1, 1, 1.1], wspace=.34))
    # (a) how locally variable each predictor is
    ax = axes[0]
    L = LV.sort_values("ratio")
    y = np.arange(len(L))
    ax.barh(y, L.ratio, color=["#1f6f8b" if r_ > .7 else "#c98b5e" if r_ > .55 else "#b5442e"
                               for r_ in L.ratio], height=.66)
    for i, r_ in enumerate(L.ratio):
        ax.text(r_ + .012, i, f"{r_:.2f}", va="center", fontsize=6.2, color=MUTED)
    ax.set_yticks(y); ax.set_yticklabels(L.mechanism, fontsize=6.8)
    ax.set_xlim(0, 1.14)
    ax.set_xlabel(f"change between sites under {radius_km} km apart,\n"
                  f"as a fraction of the national spread")
    ax.set_title(f"a   How local each mechanism is\n({n_pairs} nearby site pairs)",
                 loc="left", fontsize=8.6)

    # (b) survival rate per mechanism
    ax = axes[1]
    R = pd.DataFrame({"mech": order,
                      "sig": [int(e[e.mechanism == mm].sig.sum()) for mm in order],
                      "sur": [int(e[e.mechanism == mm].survives_spatial.sum())
                              for mm in order]})
    R["pct"] = 100 * R.sur / R.sig.replace(0, np.nan)
    y = np.arange(len(R))
    ax.barh(y, R.pct.fillna(0),
            color=["#1f6f8b" if p > 50 else "#c98b5e" if p > 0 else "#b5442e"
                   for p in R.pct.fillna(0)], height=.66)
    for i, r_ in R.iterrows():
        ax.text((r_.pct if np.isfinite(r_.pct) else 0) + 2.5, i,
                f"{int(r_.sur)} of {int(r_.sig)}" if r_.sig else "none clear",
                va="center", fontsize=6.2, color=MUTED)
    ax.set_yticks(y); ax.set_yticklabels(R.mech, fontsize=6.8); ax.invert_yaxis()
    ax.set_xlim(0, 122); ax.set_xticks([0, 25, 50, 75, 100])
    ax.set_xlabel("% of clear effects still clear with\ngeography held constant")
    ax.set_title("b   Which mechanisms survive", loc="left", fontsize=8.6)

    # (c) the relationship: local variability predicts survival
    ax = axes[2]
    P = LV.dropna(subset=["ratio", "pct"])
    ax.scatter(P.ratio, P.pct, s=42, c="#1f6f8b", lw=.4, edgecolor="white", zorder=3)
    # Hand-placed offsets: four mechanisms cluster in the upper right and collide at any
    # single offset. Keys are mechanism names, values are (dx, dy) in points.
    OFF = {"human disturbance": (0, -13), "predator abundance": (-4, 9),
           "relative abundance": (2, -13), "predator richness": (0, 9),
           "summer heat": (6, 9), "vegetation": (0, 9), "terrain": (0, 9),
           "agriculture": (0, 9)}
    for _, r_ in P.iterrows():
        dx, dy = OFF.get(r_.mechanism, (0, 9))
        ax.annotate(r_.mechanism, (r_.ratio, r_.pct), xytext=(dx, dy),
                    textcoords="offset points", fontsize=6.0, ha="center", color=INK)
    rho = float(P[["ratio", "pct"]].corr(method="spearman").iloc[0, 1])
    # One mechanism breaks the pattern. Identify it FROM THE DATA rather than naming it in a
    # string: a hardcoded name silently outlives the result it describes, which is exactly how
    # the panel this replaced came to caption one predictor with another's rationale.
    # The exception is the least locally variable mechanism whose survival is nonetheless
    # above the median across mechanisms.
    # The exception is the mechanism whose survival most exceeds what its locality predicts:
    # the largest positive residual in rank space. Reported only when that residual is at
    # least 2 ranks, so a near-perfect ordering yields no claim rather than a spurious one.
    Q = P.assign(r_ratio=P.ratio.rank(), r_pct=P.pct.rank())
    Q["resid"] = Q.r_pct - Q.r_ratio
    top = Q.nlargest(1, "resid")
    ag = top if len(top) and float(top.resid.iloc[0]) >= 2 else P.iloc[:0]
    ax.set_xlabel(f"change between sites under {radius_km} km apart,\n"
                  f"as a fraction of the national spread")
    ax.set_ylabel("% of clear effects surviving")
    ax.set_xlim(P.ratio.min() - .09, P.ratio.max() + .09)
    ax.set_ylim(-26, 122)
    note = f"rank correlation {rho:+.2f} across {len(P)} mechanisms"
    if len(ag):
        note += (f"\n{ag.mechanism.iloc[0]} is the exception: survives more\n"
                 f"({float(ag.pct.iloc[0]):.0f}%) than its locality "
                 f"({float(ag.ratio.iloc[0]):.2f}) predicts")
    ax.text(.03, .04, note, transform=ax.transAxes, fontsize=6.2, color=INK, va="bottom")
    ax.set_title("c   Mechanisms varying between neighbours mostly\nsurvive; smooth ones "
                 "mostly do not", loc="left", fontsize=8.6)
    nsig, nsur = int(e.sig.sum()), int(e.survives_spatial.sum())
    fig.suptitle(f"Holding geography constant: {nsur} of {nsig} clear effects survive, and "
                 f"which ones is predicted by how locally the mechanism varies",
                 fontsize=9.8, y=1.03)
    return fig

def fig10_counting_noise(D, style=None):
    """The counting-noise test, for the three predictors built from detection counts.

    Applies ONLY to predictors derived from detection counts. The five environmental
    covariates are not count-derived, so the test does not apply to them and they are absent
    here by construction rather than by omission.
    """
    if style:
        style()
    nt = D["null"].copy()
    mechs = nt.mechanism.dropna().unique().tolist()

    fig, axes = plt.subplots(1, 3, figsize=(13.2, 4.2),
                             gridspec_kw=dict(width_ratios=[1, 1, 1], wspace=.32))
    # (a) observed effect against what pure counting noise reproduces
    ax = axes[0]
    for mm, col in zip(mechs, ["#1f6f8b", "#c98b5e", "#7a5aa8"]):
        s_ = nt[nt.mechanism == mm]
        ax.scatter(s_.null_abs_median, s_.obs_beta.abs(), s=14, c=col, lw=0, alpha=.85,
                   label=mm)
    hi = float(np.nanpercentile(np.r_[nt.obs_beta.abs(), nt.null_abs_median], 99)) * 1.08
    ax.plot([0, hi], [0, hi], color=MUTED, lw=.9, ls="--")
    ax.set_xlim(0, hi); ax.set_ylim(0, hi)
    ax.set_xlabel("effect size counting noise alone reproduces")
    ax.set_ylabel("effect size observed")
    ax.legend(fontsize=6.2, frameon=False, loc="lower right")
    ax.text(.03, .97, "on the dashed line, the effect is\nwhat noise alone would give",
            transform=ax.transAxes, fontsize=6.0, color=MUTED, va="top")
    ax.set_title("a   Observed against simulated", loc="left", fontsize=8.6)

    # (b) share of the observed effect the null reproduces
    ax = axes[1]
    for i, mm in enumerate(mechs):
        v = nt[nt.mechanism == mm].abs_frac_reproduced.dropna().clip(0, 2)
        xj = np.random.default_rng(i).normal(0, .07, len(v))
        ax.scatter(v, i + xj, s=11, c="#7fa9bb", lw=0, alpha=.8, zorder=3)
        ax.plot([float(np.median(v))], [i], marker="|", ms=15, color=INK, zorder=4)
        ax.text(1.92, i - .28, f"median {np.median(v):.2f}", fontsize=6.0, color=MUTED,
                ha="right")
    ax.axvline(1, color="#b5442e", lw=1.0, ls=":")
    ax.text(1.03, -.42, "noise reproduces\nthe whole effect", fontsize=6.0,
            color="#b5442e", va="top")
    ax.text(.99, .03, "values above 2 are drawn at 2", transform=ax.transAxes,
            fontsize=5.8, color=MUTED, ha="right")
    ax.set_yticks(range(len(mechs))); ax.set_yticklabels(mechs, fontsize=6.8)
    ax.set_xlim(-.05, 2.0); ax.invert_yaxis()
    ax.set_xlabel("share of the observed effect that counting noise reproduces")
    ax.set_title("b   How much is noise", loc="left", fontsize=8.6)

    # (c) what is left
    ax = axes[2]
    y = np.arange(len(mechs))
    sig = [int(nt[nt.mechanism == mm].obs_sig.sum()) for mm in mechs]
    sur = [int(nt[nt.mechanism == mm].survives_null.sum()) for mm in mechs]
    ax.barh(y, sig, color="#dfe5e8", height=.64, label="clear before the test")
    ax.barh(y, sur, color="#1f6f8b", height=.64, label="still clear after")
    for i, (s_, u_) in enumerate(zip(sig, sur)):
        ax.text(s_ + .4, i, f"{u_} of {s_}", va="center", fontsize=6.4, color=MUTED)
    ax.set_yticks(y); ax.set_yticklabels(mechs, fontsize=6.8); ax.invert_yaxis()
    ax.set_xlabel("species-measure combinations")
    ax.set_xlim(0, max(sig) * 1.32)
    ax.legend(fontsize=6.2, frameon=False, loc="lower right")
    ax.set_title("c   What survives the test", loc="left", fontsize=8.6)
    fig.suptitle("Counting-noise test: applies only to the three predictors built from "
                 "detection counts, never to the environmental covariates",
                 fontsize=9.8, y=1.03)
    return fig


def fig11_skill_and_maps(D, style=None):
    """Out-of-sample skill for every combination, and the surfaces that earned a map."""
    if style:
        style()
    cv, sd, ps = D["cv"], D["surface_diag"], D["surfaces"]

    fig = plt.figure(figsize=(13.4, 7.8))
    gs = fig.add_gridspec(2, 4, height_ratios=[1, 1.15], hspace=.34, wspace=.14)

    # (a) skill for every species-measure combination, by predictor set
    ax = fig.add_subplot(gs[0, :2])
    sets = cv.predictor_set.dropna().unique().tolist()
    for i, st in enumerate(sets):
        s_ = cv[cv.predictor_set == st]
        xj = np.random.default_rng(i).normal(0, .08, len(s_))
        won = s_.beats_null.fillna(False).values.astype(bool)
        ax.scatter(s_.skill[~won], i + xj[~won], s=11, c="#ffffff", edgecolor="#c3cbd0",
                   lw=.5, zorder=2)
        ax.scatter(s_.skill[won], i + xj[won], s=16, c="#1f6f8b", lw=0, zorder=3)
        ax.plot([float(np.nanmedian(s_.skill))], [i], marker="|", ms=15, color=INK, zorder=4)
        ax.text(.985, 1 - (i + .62) / len(sets), f"{int(won.sum())} of {len(s_)} beat the null",
                transform=ax.transAxes, fontsize=6.2, color=MUTED, ha="right")
    ax.axvline(0, color="#b5442e", lw=1.0, ls=":")
    # A handful of folds give large negative skill and would compress everything else to a
    # line. Clip the view and say how many points fall outside it.
    lo_c = float(np.nanpercentile(cv.skill, 2)) - .05
    n_off = int((cv.skill < lo_c).sum())
    ax.set_xlim(lo_c, float(np.nanmax(cv.skill)) * 1.35 + .02)
    if n_off:
        ax.text(.015, .04, f"{n_off} rows fall below {lo_c:.2f} and are outside this view",
                transform=ax.transAxes, fontsize=6.0, color=MUTED)
    ax.set_yticks(range(len(sets))); ax.set_yticklabels(sets, fontsize=6.8)
    ax.invert_yaxis()
    ax.set_xlabel("skill against one nationwide curve\n(0 means no better than the same "
                  "rhythm everywhere)")
    ax.set_title("a   Out-of-sample skill, every combination", loc="left", fontsize=8.8)

    # (b) roughness against skill for the mapped surfaces
    ax = fig.add_subplot(gs[0, 2:])
    ax.axhline(0, color="#b5442e", lw=.9, ls=":")
    ax.axvline(1, color=MUTED, lw=.8, ls="--")
    for _, r_ in sd.iterrows():
        ax.errorbar(r_.roughness_ratio, r_.cv_skill,
                    yerr=[[r_.cv_skill - r_.cv_lo], [r_.cv_hi - r_.cv_skill]],
                    fmt="o", ms=6, lw=1.1, color="#1f6f8b", ecolor="#7fa9bb", capsize=2)
        ax.annotate(f"{r_.species}\n{MEASURE_LABEL.get(r_.measure, r_.measure)}",
                    (r_.roughness_ratio, r_.cv_skill), xytext=(7, 0),
                    textcoords="offset points", fontsize=6.0, va="center", color=INK)
    ax.set_xlabel("neighbouring-cell change / site-to-site spread\n"
                  "(above 1 means the surface is rougher than the real variation)")
    ax.set_ylabel("skill against one\nnationwide curve")
    ax.yaxis.set_label_position("right"); ax.yaxis.tick_right()
    ax.set_xlim(0, max(1.25, float(sd.roughness_ratio.max()) * 1.45))
    ax.set_title("b   The surfaces that earned a map", loc="left", fontsize=8.8)

    # (c-f) the surfaces themselves
    for k, (_, r_) in enumerate(sd.iterrows()):
        if k >= 4:
            break
        ax = fig.add_subplot(gs[1, k])
        g = ps[(ps.species == r_.species) & (ps.measure == r_.measure) & ps.drawn.fillna(False)]
        draw_states(ax, D["states"], lw=.30, color="#c9cfd4")
        cyc = r_.measure == "peak_h"
        v = g.pred.values
        # NOT g.gx / g.gy: those columns are integer GRID INDICES (range -94..90), not the
        # Albers coordinates the state outlines use. Project from lon/lat instead.
        px, py = albers(g.lon.values, g.lat.values)
        sc = ax.scatter(px, py, c=v, s=2.2,
                        cmap=CYCLIC_CMAP if cyc else SEQ_CMAP, lw=0,
                        vmin=0 if cyc else np.nanpercentile(v, 2),
                        vmax=24 if cyc else np.nanpercentile(v, 98))
        ax.set_xlim(-.385, .375); ax.set_ylim(-.225, .262)
        ax.set_aspect("equal"); ax.axis("off")
        cb = fig.colorbar(sc, ax=ax, fraction=.030, pad=.005, shrink=.68)
        cb.ax.tick_params(labelsize=5.4)
        ax.set_title(f"{'cdef'[k]}   {r_.species}\n{MEASURE_LABEL.get(r_.measure, r_.measure)}",
                     loc="left", fontsize=7.6)
        ax.text(.02, .04, f"{int(r_.n_cells_drawn):,} cells\n"
                          f"median interval width {np.nanmedian(g.ci95_width):.1f}",
                transform=ax.transAxes, fontsize=5.6, color=MUTED)
    nwon = int(cv.beats_null.fillna(False).sum())
    fig.suptitle(f"Out-of-sample skill and the four surfaces that passed: {nwon} of {len(cv)} "
                 f"combination-and-predictor-set rows beat a single nationwide curve",
                 fontsize=9.8, y=.965)
    return fig


# Which figures document HOW the analysis was done and which report WHAT it found. The methods
# set exists for review and for a supplement; it is not intended for the main paper. The
# results set is where detail belongs, so keep those panels rich even when trimming elsewhere.
ROLE = {
    "fig01_data_coverage": "methods",
    "fig02_species_curves": "results",
    "fig03_effort_offset": "methods",
    "fig04_measures_reliability": "methods",
    "fig05_covariate_maps": "methods",
    "fig06_timestamp_qc": "methods",
    "fig07_model_effects": "results",
    "fig08_predator_abundance": "results",
    "fig09_spatial_control": "results",
    "fig10_counting_noise": "results",
    "fig11_skill_and_maps": "results",
}

FIGURES = {
    "fig01_data_coverage": fig01_data_coverage,
    "fig02_species_curves": fig02_species_curves,
    "fig03_effort_offset": fig03_effort_offset,
    "fig04_measures_reliability": fig04_measures_reliability,
    "fig05_covariate_maps": fig05_covariate_maps,
    "fig06_timestamp_qc": fig06_timestamp_qc,
    "fig07_model_effects": fig07_model_effects,
    "fig08_predator_abundance": fig08_predator_abundance,
    "fig09_spatial_control": fig09_spatial_control,
    "fig10_counting_noise": fig10_counting_noise,
    "fig11_skill_and_maps": fig11_skill_and_maps,
}


def figure_index():
    """One row per figure: name, role, and whether it is a main-paper candidate."""
    return pd.DataFrame([{"figure": k, "role": ROLE.get(k, "unclassified"),
                          "main_paper_candidate": ROLE.get(k) == "results"}
                         for k in FIGURES])


def render_all(host, outdir=".", style=None, only=None, role=None):
    """Render every registered figure to PNG at 300 dpi. Returns {name: path}."""
    import os
    os.makedirs(outdir, exist_ok=True)
    D = load_all(host)
    made = {}
    for name, fn in FIGURES.items():
        if only and name not in only:
            continue
        if role and ROLE.get(name) != role:
            continue
        if role and ROLE.get(name) != role:
            continue
        fig = fn(D, style=style)
        path = os.path.join(outdir, f"{name}.png")
        fig.savefig(path, dpi=300, bbox_inches="tight")
        made[name] = path
        plt.close(fig)
    return made
